### ISSUE TITLE
cannot setup local ldap server

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [kwk/docker-registry-setup#20]
good day
i try to setup registry with company ldap server:
```
ldap_auth:
  addr: "192.168.0.10:389"
  tls: false
  bind_dn: "CN=Administrator,CN=Users,DC=company,DC=local"
  bind_password_file: /tmp/ldap_password.txt.clean
  base: "CN=Users,DC=singularis,DC=local"
  filter: "(&(sAMAccountName=${account})(objectClass=user))"
```
also i put password for account into /tmp/ldap_password.txt.clean

but when i try to login to registry i get following output:
```
registry_1  | 172.17.0.1 - - [05/Dec/2019:13:07:33 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/19.03.0-rc2 go/go1.12.5 git-commit/f97efcc kernel/4.9.125-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.0-rc2 \\(windows\\))"
registry_1  | time="2019-12-05T13:07:33.1161369Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.2 http.request.host="0.0.0.0:5000" http.request.id=ba5b30c2-7f18-401f-ac17-178235ec7258 http.request.method=GET http.request.remoteaddr="172.17.0.1:45954" http.request.uri="/v2/" http.request.useragent="docker/19.03.0-rc2 go/go1.12.5 git-commit/f97efcc kernel/4.9.125-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.0-rc2 \(windows\))"
auth_1      | I1205 13:07:33.134897      11 server.go:358] Request: &{Method:GET URL:/auth?account=testuser&client_id=docker&offline_token=true&service=my.docker.registry Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Encoding:[gzip] Authorization:[Basic dGVzdHVzZXI6cGFzc3BocmFzZQ==] Connection:[close] User-Agent:[docker/19.03.0-rc2 go/go1.12.5 git-commit/f97efcc kernel/4.9.125-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.0-rc2 \(windows\))]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:true Host:0.0.0.0:5001 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.17.0.1:40550 RequestURI:/auth?account=testuser&client_id=docker&offline_token=true&service=my.docker.registry TLS:0xc0003a22c0 Cancel:<nil> Response:<nil> ctx:0xc0000782c0}
auth_1      | I1205 13:07:33.134995      11 server.go:402] Auth request: {testuser:***@172.17.0.1:40550 []}
auth_1      | I1205 13:07:33.135008      11 server.go:241] Authn static testuser -> false, map[], did not match any rule
auth_1      | I1205 13:07:33.135062      11 ldap_auth.go:126] Bind read-only user (DN = CN=Administrator,CN=Users,DC=company,DC=local)
auth_1      | I1205 13:07:33.135155      11 server.go:3055] http: panic serving 172.17.0.1:40550: runtime error: invalid memory address or nil pointer dereference
auth_1      | goroutine 36 [running]:
auth_1      | net/http.(*conn).serve.func1(0xc0000981e0)
auth_1      |   /usr/local/go/src/net/http/server.go:1767 +0x139
auth_1      | panic(0xb66aa0, 0x122a490)
auth_1      |   /usr/local/go/src/runtime/panic.go:679 +0x1b2
auth_1      | sync.(*Mutex).Lock(...)
auth_1      |   /usr/local/go/src/sync/mutex.go:74
auth_1      | github.com/go-ldap/ldap.(*Conn).Close(0x0)
auth_1      |   /go/pkg/mod/github.com/go-ldap/ldap@v3.0.3+incompatible/conn.go:207 +0x3e
auth_1      | panic(0xb66aa0, 0x122a490)
auth_1      |   /usr/local/go/src/runtime/panic.go:679 +0x1b2
auth_1      | github.com/go-ldap/ldap.(*Conn).nextMessageID(...)
auth_1      |   /go/pkg/mod/github.com/go-ldap/ldap@v3.0.3+incompatible/conn.go:235
auth_1      | github.com/go-ldap/ldap.(*Conn).SimpleBind(0x0, 0xc00039b6e0, 0x0, 0x0, 0x0)
auth_1      |   /go/pkg/mod/github.com/go-ldap/ldap@v3.0.3+incompatible/bind.go:54 +0xa5
auth_1      | github.com/go-ldap/ldap.(*Conn).Bind(...)
auth_1      |   /go/pkg/mod/github.com/go-ldap/ldap@v3.0.3+incompatible/bind.go:116
auth_1      | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).bindReadOnlyUser(0xc0000a41c0, 0x0, 0x0, 0x0)
auth_1      |   /src/auth_server/authn/ldap_auth.go:127 +0x1c0
auth_1      | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).Authenticate(0xc0000a41c0, 0xc000358660, 0x1f, 0xc00009c4d0, 0xa, 0x0, 0x0, 0x0, 0x0)
auth_1      |   /src/auth_server/authn/ldap_auth.go:74 +0x134
auth_1      | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).Authenticate(0xc0000ad2c0, 0xc000098280, 0xc65ae3, 0x11, 0xc00039ba98, 0x1)
auth_1      |   /src/auth_server/server/server.go:240 +0xbd
auth_1      | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).doAuth(0xc0000ad2c0, 0xd706a0, 0xc0003f20e0, 0xc000390300)
auth_1      |   /src/auth_server/server/server.go:404 +0x201
auth_1      | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).ServeHTTP(0xc0000ad2c0, 0xd706a0, 0xc0003f20e0, 0xc000390300)
auth_1      |   /src/auth_server/server/server.go:367 +0x3e6
auth_1      | net/http.serverHandler.ServeHTTP(0xc0002fc2a0, 0xd706a0, 0xc0003f20e0, 0xc000390300)
auth_1      |   /usr/local/go/src/net/http/server.go:2802 +0xa4
auth_1      | net/http.(*conn).serve(0xc0000981e0, 0xd722e0, 0xc000078240)
auth_1      |   /usr/local/go/src/net/http/server.go:1890 +0x875
auth_1      | created by net/http.(*Server).Serve
auth_1      |   /usr/local/go/src/net/http/server.go:2927 +0x38e
```

i'm also try to specify user as company\testuser but the result is same
i try to use specified dn in ldap browser and can successfully obtain user

my ldap base on win 2008 r2 active directory controller

**Comment by anatoly-kryzhanovsky** [comment]
ok, i found my mistake.. config attribute tls must have value as "none" or empty string...
